name: VanDragt
url: http://vandragt.com
author: Sander van Dragt
markdown: kramdown
pygments: true
paginate: 10
permalink: pretty
encoding: utf-8
gems:
  - jekyll-redirect-from
include: ['_pages']
relative_permalinks: false